platform:
    - x86
    - x64

environment:
    matrix:
        - VSVER: 14
        

before_build:
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
           
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            
        }
   
   - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
    - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
   

build_script:
  - mkdir build && cd build
  - set CURL_INCLUDE_DIR=%INSTALL_PREFIX%\include
  - set CURL_LIBRARY=%INSTALL_PREFIX%\lib\libcurl.lib
  - set CMAKE_PUGIXML_FLAGS=-DPUGIXML_LIBRARY=%INSTALL_PREFIX%\lib\pugixml.lib -DPUGIXML_INCLUDE_DIR=%INSTALL_PREFIX%\include
  - set CMAKE_CURL_FLAGS=-DCURL_STATICLIB:BOOL=%BUILD_SHARED% -DCURL_INCLUDE_DIR:STRING=%CURL_INCLUDE_DIR% -DCURL_LIBRARY=%CURL_LIBRARY%
  - set CMAKE_OPENSSL_FLAGS=-DOPENSSL_LIBRARIES=%INSTALL_PREFIX%\lib\libcrypto.lib;%INSTALL_PREFIX%\lib\libssl.lib 
  - cmake .. -G "NMake Makefiles" %CMAKE_PUGIXML_FLAGS% %CMAKE_CURL_FLAGS% %CMAKE_OPENSSL_FLAGS% -DBUILD_SHARED_LIBS=%BUILD_SHARED%
  - nmake
  - nmake install
